name: build_linux

on:
  push:
jobs:
  build:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Build Project
        uses: threeal/cmake-action@v2.1.0
        with:
          build-dir: build
          generator: Ninja
          args: --preset=linux-debug
