name: build_aarch64

on:
  push:
jobs:
  build-aarch64:
    name: Linux aarch64
    runs-on: ubuntu-24.04-arm
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure and Build
      run: |
        cmake --preset linux-arm64-ci
        cmake --build --preset linux-arm64-ci -- -k0
    #- name: Upload binary artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #      name: usearch12.arch64-binary
    #      path: /home/runner/work/usearch12/usearch12/bin/usearch12
