name: build_windows

on:
  push:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Project
      uses: threeal/cmake-action@v2.1.0
      with:
        build-dir: build
        generator: Ninja
        args: --preset=Win-x64-Debug
        build-args: --preset=windows-ci
    #- name: Upload binary artifact
    #  uses: actions/upload-artifact@v4
    #  with:
    #      name: usearch12-windows-binary.exe
    #      path: D:\a\usearch12\usearch12\src\x64\Release\usearch12.exe
