name: build_linux

on:
  push:
jobs:
  build:
    name: Linux x86_64
    runs-on: ubuntu-latest
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Configure and Build
        run: |
          cmake --preset linux-debug
          cmake --build --preset linux-debug -- -k0
